services:
  kiso:
    build: .
    container_name: kiso
    ports:
      - "8333:8333"
    volumes:
      - ${KISO_DATA:-~/.kiso}:/root/.kiso
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
