services:
  kiso:
    build: .
    container_name: kiso
    ports:
      - "8333:8333"
    volumes:
      - kiso-data:/root/.kiso
    env_file:
      - path: .env
        required: false
    restart: unless-stopped

volumes:
  kiso-data:
